version: '3.8'
services:
    ui:
     container_name: ui
     build:
      context: ./ui
      dockerfile: Dockerfile
     volumes:
      - './ui:/usr/src/app'
      - '/usr/src/app/node_modules'
     ports:
      - 3001:3000
     environment:
      - CHOKIDAR_USEPOLLING=true
    #  links:
    #   - api
     networks:
      - bonat-network

    api:
     container_name: api
     build:
      context: ./api
      dockerfile: Dockerfile
     volumes:
      - './api:/usr/src/app'
      - '/usr/src/app/node_modules'
     restart: always
     ports:
      - "3002:3000"
     depends_on:
      - mongodb
     networks:
      - bonat-network

    mongodb:
     image: mongo
     restart: always
     container_name: mongodb
     volumes:
      - ./data-node:/data/db
     ports:
      - 27017:27017
     command: mongod --noauth
     networks:
      - bonat-network
networks:
    bonat-network:
        driver: bridge